-- MySQL Script generated by MySQL Workbench
-- 08/04/15 14:20:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dtd_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dtd_schema` ;
CREATE SCHEMA IF NOT EXISTS `dtd_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dtd_schema` ;

-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_admin` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_admin` (
  `admin_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_user` VARCHAR(45) NOT NULL,
  `admin_pass` VARCHAR(40) NOT NULL,
  `admin_name` VARCHAR(45) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `admin_user_UNIQUE` ON `dtd_schema`.`dtd_admin` (`admin_user` ASC);


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_custdep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_custdep` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_custdep` (
  `dep_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dep_custid` INT(10) UNSIGNED NOT NULL,
  `dep_date` DATETIME NOT NULL,
  `dep_amount` DECIMAL(8,2) NOT NULL,
  `dep_transno` VARCHAR(45) NOT NULL,
  `dep_bankname` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`dep_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_cust_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_cust_grade` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_cust_grade` (
  `grade_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `grade_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`grade_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_gradeprice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_gradeprice` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_gradeprice` (
  `gp_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gp_fromdt` DATETIME NOT NULL,
  `gp_todt` DATETIME NOT NULL,
  `gp_grade` SMALLINT(5) UNSIGNED NOT NULL,
  `gp_disc` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`gp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_itemprice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_itemprice` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_itemprice` (
  `gi_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gi_type` SMALLINT(5) UNSIGNED NOT NULL,
  `gi_price` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`gi_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_item_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_item_type` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_item_type` (
  `type_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_order` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_order` (
  `order_id` BIGINT(40) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_custid` INT(10) UNSIGNED NOT NULL,
  `order_vendorid` INT(11) NOT NULL,
  `order_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order_recipient` VARCHAR(100) NOT NULL,
  `order_address` VARCHAR(255) NOT NULL,
  `order_zipcode` VARCHAR(6) NOT NULL,
  `order_telp` VARCHAR(10) NULL DEFAULT NULL,
  `order_telno` VARCHAR(20) NULL DEFAULT NULL,
  `order_mobp` VARCHAR(10) NULL DEFAULT NULL,
  `order_mobno` VARCHAR(20) NULL DEFAULT NULL,
  `order_typeid` SMALLINT(4) UNSIGNED NOT NULL,
  `order_amount` DECIMAL(8,2) NOT NULL,
  `order_itemname` VARCHAR(100) NOT NULL,
  `order_memo` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_users` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  `user_add` VARCHAR(200) NULL,
  `user_zipcode` VARCHAR(5) NOT NULL,
  `user_tel` VARCHAR(20) NULL,
  `user_mob` VARCHAR(20) NOT NULL,
  `user_balance` DECIMAL(8,2) NULL DEFAULT '0.00',
  `user_staffname` VARCHAR(45) NULL,
  `user_stafftel` VARCHAR(20) NULL,
  `user_memo` TEXT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '0',
  `user_role` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `user_email_UNIQUE` ON `dtd_schema`.`dtd_users` (`user_email` ASC);

INSERT INTO `dtd_schema`.`dtd_users` (`user_id`, `user_name`, `user_email`, `user_pass`, `user_add`, `user_zipcode`, `user_tel`, `user_mob`, `user_balance`, `user_staffname`, `user_stafftel`, `user_memo`, `is_active`, `user_role`) VALUES (NULL, 'Vimal Ghorecha', 'vimal14569@gmail.com', 'vigour', NULL, '36005', NULL, '7405100630', '0.00', NULL, NULL, NULL, '1', 'customer');
-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_vendorpay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_vendorpay` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_vendorpay` (
  `dep_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pay_vendorid` INT(10) UNSIGNED NOT NULL,
  `pay_date` DATETIME NOT NULL,
  `pay_amount` DECIMAL(8,2) NOT NULL,
  `pay_transno` VARCHAR(45) NOT NULL,
  `pay_bankacno` VARCHAR(30) NOT NULL,
  `pay_bankname` VARCHAR(100) NULL,
  PRIMARY KEY (`dep_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_vendorprice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_vendorprice` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_vendorprice` (
  `vp_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gp_vendorid` INT(10) UNSIGNED NOT NULL,
  `gp_typeid` SMALLINT(5) UNSIGNED NOT NULL,
  `gp_price` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`vp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_cust`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_cust` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_cust` (
  `cust_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `user_regno` VARCHAR(45) NOT NULL,
  `user_site` VARCHAR(255) NULL,
  `vendor_id` INT(20) UNSIGNED NULL DEFAULT NULL,
  `user_grade` SMALLINT(5) UNSIGNED NULL,
  `user_lob` VARCHAR(45) NULL,
  `user_sercomp` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dtd_schema`.`dtd_vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dtd_schema`.`dtd_vendor` ;

CREATE TABLE IF NOT EXISTS `dtd_schema`.`dtd_vendor` (
  `vendor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `vendor_taxno` VARCHAR(45) NOT NULL,
  `vendor_hq1` VARCHAR(45) NULL,
  `vendor_hq2` VARCHAR(45) NULL,
  `vendor_hq3` VARCHAR(45) NULL,
  `pay_bankacno` VARCHAR(30) NOT NULL,
  `pay_bankname` VARCHAR(100) NULL,
  PRIMARY KEY (`vendor_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
